version: 2.1 
jobs:
  build:
    docker:
      - image: cimg/node:15.0.1
    steps:
      - checkout
      - run: echo "npm installing"
      - run: node --version
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: cimg/node:15.0.1 
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: node --version
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: cimg/node:15.0.1 
    steps:
      - checkout
      - run: echo "Hellllloooo!!! "
workflows:
  version: 2.1 
  build_test_and_linting:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere